pragma Singleton

import Quickshell
import QtQuick

Singleton {
    // Semantic Material colors generated by Matugen
    readonly property color primary: "#80d4db"
    readonly property color overPrimary: "#00363a"

    readonly property color secondary: "#b1cbce"
    readonly property color overSecondary: "#1b3436"

    readonly property color tertiary: "#b7c7ea"
    readonly property color overTertiary: "#20304c"

    readonly property color errorColor: "#ffb4ab"
    readonly property color overError: "#690005"

    readonly property color surface: "#0e1415"
    readonly property color overSurface: "#dde4e4"
    readonly property color surfaceVariant: "#3f4849"
    readonly property color overSurfaceVariant: "#bec8c9"

    readonly property color outline: "#899393"
    readonly property color outlineVariant: "#3f4849"

    // Derived/general colors
    readonly property color accent: primary

    readonly property color widget: windowBackground
    readonly property color widgetHover: "#252b2c"
    readonly property color widgetContainer: accent
    readonly property color doubleWidgetSeparator: outlineVariant

    readonly property color windowBackground: surface

    readonly property color launcherPlaceholderTextColor: overSurfaceVariant

    // Constant colors
    readonly property color black: Qt.rgba(0, 0, 0)

    readonly property color nightlightToggledOn: Qt.rgba(1, 0.93, 0.56)
    readonly property color nightlightHoverToggledOn: Qt.rgba(1, 0.96, 0.76)
    readonly property color nightlightTextToggledOn: black

    readonly property color indicatorHigh: Qt.rgba(1, 0.48, 0)
    readonly property color indicatorCritical: Qt.rgba(1, 0, 0)

    // Widget colors
    readonly property color system: Config.showWidgetContainer ? accent : primary
    readonly property color workspaces: Config.showWidgetContainer ? accent : secondary
    readonly property color audio: Config.showWidgetContainer ? accent : tertiary
    readonly property color nightLight: Config.showWidgetContainer ? accent : primary
    readonly property color dateTime: Config.showWidgetContainer ? accent : secondary
    readonly property color wifi: Config.showWidgetContainer ? accent : tertiary
    readonly property color sensors: Config.showWidgetContainer ? accent : primary
    readonly property color weather: Config.showWidgetContainer ? accent : secondary
    readonly property color volume: Config.showWidgetContainer ? accent : tertiary
}