pragma Singleton

import Quickshell
import QtQuick

Singleton {
    // Semantic Material colors generated by Matugen
    readonly property color primary: "{{ colors.primary.default.hex }}"
    readonly property color overPrimary: "{{ colors.on_primary.default.hex }}"

    readonly property color secondary: "{{ colors.secondary.default.hex }}"
    readonly property color overSecondary: "{{ colors.on_secondary.default.hex }}"

    readonly property color tertiary: "{{ colors.tertiary.default.hex }}"
    readonly property color overTertiary: "{{ colors.on_tertiary.default.hex }}"

    readonly property color errorColor: "{{ colors.error.default.hex }}"
    readonly property color overError: "{{ colors.on_error.default.hex }}"

    readonly property color surface: "{{ colors.surface.default.hex }}"
    readonly property color overSurface: "{{ colors.on_surface.default.hex }}"
    readonly property color surfaceVariant: "{{ colors.surface_variant.default.hex }}"
    readonly property color overSurfaceVariant: "{{ colors.on_surface_variant.default.hex }}"

    readonly property color outline: "{{ colors.outline.default.hex }}"
    readonly property color outlineVariant: "{{ colors.outline_variant.default.hex }}"

    // Derived/general colors
    readonly property color accent: primary

    readonly property color widget: windowBackground
    readonly property color widgetHover: "{{ colors.surface_container_high.default.hex }}"
    readonly property color widgetContainer: accent
    readonly property color separator: outlineVariant

    readonly property color windowBackground: surface

    readonly property color launcherPlaceholderTextColor: overSurfaceVariant

    // Constant colors
    readonly property color black: Qt.rgba(0, 0, 0)

    readonly property color nightlightToggledOn: Qt.rgba(1, 0.93, 0.56)
    readonly property color nightlightHoverToggledOn: Qt.rgba(1, 0.96, 0.76)
    readonly property color nightlightTextToggledOn: black

    readonly property color indicatorHigh: Qt.rgba(1, 0.48, 0)
    readonly property color indicatorCritical: Qt.rgba(1, 0, 0)

    // Widget colors
    readonly property color system: Config.showWidgetContainer ? accent : primary
    readonly property color workspaces: Config.showWidgetContainer ? accent : secondary
    readonly property color audio: Config.showWidgetContainer ? accent : secondary
    readonly property color nightLight: Config.showWidgetContainer ? accent : secondary
    readonly property color dateTime: Config.showWidgetContainer ? accent : tertiary
    readonly property color wifi: Config.showWidgetContainer ? accent : secondary
    readonly property color sensors: Config.showWidgetContainer ? accent : secondary
    readonly property color weather: Config.showWidgetContainer ? accent : secondary
    readonly property color volume: Config.showWidgetContainer ? accent : tertiary
}