general {
    hide_cursor = true
}

background {
    monitor =

    reload_time = 0
    reload_cmd = awww query | sed -n 's/.*currently displaying: image: //p' | head -n1

    blur_passes = 3
    blur_size = 5
    noise = 0.02

    contrast = 0.9
    brightness = 0.8
    vibrancy = 0.15
    vibrancy_darkness = 0.0
}

# Time
label {
    monitor =

    text = cmd[update:1000] date +"%H:%M"
    color = rgba(FFFFFFFF)

    font_family = JetBrainsMono Font SemiBold
    font_size = 88

    position = 0, 220
    halign = center
    valign = center
}

# Date
label {
    monitor =

    text = cmd[update:1000] date +"%A, %B %d"
    color = rgba(DDDDDDFF)

    font_family = JetBrainsMono Font
    font_size = 24

    position = 0, 130
    halign = center
    valign = center
}

# User name
label {
    monitor =

    text =
    color = rgba(CCCCCCFF)

    font_family = JetBrainsMono Font
    font_size = 20

    position = 0, -50
    halign = center
    valign = center
}

# Password box
input-field {
    monitor =

    size = 200, 56

    position = 0, -140
    halign = center
    valign = center

    rounding = 999
    outline_thickness = 0

    inner_color = rgba(00000000)
    font_color = rgba(FFFFFFFF)

    dots_center = true
    dots_spacing = 0.35
    dots_rounding = -1

    fade_on_empty = false

    check_color = rgba(00000000) 
    fail_color = rgba(00000000) 

    placeholder_text =
}