hl.on("hyprland.start", function()
    hl.exec_cmd("systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
    hl.exec_cmd("dbus-update-activation-environment --systemd --all")
    hl.exec_cmd("hyprsunset")
    hl.exec_cmd("qs --no-duplicate")
    hl.exec_cmd("awww-daemon")
    hl.exec_cmd("hypridle")
end)