general {
    lock_cmd = ~/.dotfiles/scripts/lock.sh
}

# Brightness timeout
listener {
    timeout = 120
    on-timeout = ddcutil --display 1 setvcp 10 15 & ddcutil --display 2 setvcp 10 15 & wait
    on-resume = ddcutil --display 1 setvcp 10 100 & ddcutil --display 2 setvcp 10 100 & wait
}

# Lock screen timeout
listener {
    timeout = 300
    on-timeout = hyprlock --config ~/.config/hyprlock/hyprlock.conf
}

# Disable monitor timeout
listener {
    timeout = 500
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}