foreground #e0e2e8
background #101418

selection_foreground #101418
selection_background #9accfa

cursor #9accfa
cursor_text_color #101418

active_border_color #9accfa
inactive_border_color #8c9198

color0  #0b0f12
color1  #ffb4ab
color2  #d2bfe7
color3  #b9c8da
color4  #9accfa
color5  #0a4a72
color6  #4f4061
color7  #c2c7cf

color8  #8c9198
color9  #e0e2e8
color10 #eddcff
color11 #d4e4f6
color12 #cde5ff
color13 #9accfa
color14 #d2bfe7
color15 #e0e2e8