foreground #dde4e4
background #0e1415

selection_foreground #0e1415
selection_background #80d4db

cursor #80d4db
cursor_text_color #0e1415

active_border_color #80d4db
inactive_border_color #899393

color0  #090f10
color1  #ffb4ab
color2  #b7c7ea
color3  #b1cbce
color4  #80d4db
color5  #004f54
color6  #374764
color7  #bec8c9

color8  #899393
color9  #dde4e4
color10 #d7e3ff
color11 #cce8ea
color12 #9df0f7
color13 #80d4db
color14 #b7c7ea
color15 #dde4e4