foreground #e1e2e8
background #101418

selection_foreground #101418
selection_background #9fcafc

cursor #9fcafc
cursor_text_color #101418

active_border_color #9fcafc
inactive_border_color #8c9199

color0  #0b0e13
color1  #ffb4ab
color2  #d6bee5
color3  #bac8db
color4  #9fcafc
color5  #174974
color6  #524060
color7  #c2c7cf

color8  #8c9199
color9  #93000a
color10 #f1daff
color11 #d6e4f7
color12 #d0e4ff
color13 #9fcafc
color14 #d6bee5
color15 #e1e2e8