# Default colors loaded when first running install.sh so that the setup works before explicitly generating color files with matugen

# --- Main Colors ---
background            #121212
foreground            #d0d0d0
cursor                #d0d0d0
cursor_text_color     #121212

selection_background  #444444
selection_foreground  #e0e0e0

url_color             #b0b0b0

# --- ANSI Colors ---
color0                #101010
color1                #a0a0a0
color2                #b0b0b0
color3                #c0c0c0
color4                #888888
color5                #909090
color6                #a8a8a8
color7                #d0d0d0

color8                #484848
color9                #c0c0c0
color10               #d0d0d0
color11               #d8d8d8
color12               #a8a8a8
color13               #b0b0b0
color14               #c0c0c0
color15               #f0f0f0

# --- Starship Prompt Bubbles ---
color255              #a8a8a8
color254              #c0c0c0
color253              #555555
color252              #b8b8b8
color251              #707070
color250              #d0d0d0
color249              #888888
color248              #b0b0b0

color232              #d8d8d8
color233              #303030
color234              #d0d0d0
color235              #383838
color236              #b8b8b8
color237              #484848
color238              #c0c0c0
color239              #505050
color240              #d8d8d8

# Matched with unthemed light/dark
color243              #b0b0b0
color244              #a0a0a0
color245              #484848

# --- UI Elements ---
active_tab_foreground   #202020
active_tab_background   #c0c0c0
inactive_tab_foreground #d8d8d8
inactive_tab_background #383838

active_border_color     #c0c0c0
inactive_border_color   #555555

# --- Marks ---
mark1_foreground        #101010
mark1_background        #d8d8d8
mark2_foreground        #181818
mark2_background        #d0d0d0
mark3_foreground        #202020
mark3_background        #b8b8b8