hide_action_hints = true

[placeholders]
# Default placeholder for all providers
"default" = { input = "Search", list = "No Results" }

# Provider-specific placeholders
"desktopapplications" = { input = "Launch App", list = "No Applications" }

# For custom menus
"menus:wallpapers" = { input = "Set Wallpaper", list = "No Wallpapers" }
