# ~/.config/matugen/config.toml

[config]
reload_apps = true

[templates]

[templates.quickshell]
input_path = "~/.dotfiles/config/matugen/templates/colors.qml"
output_path = "~/.dotfiles/config/quickshell/Colors.qml"
post_hook = "hyprctl reload"

[templates.hyprland]
input_path = "~/.dotfiles/config/matugen/templates/hyprland.lua"
output_path = "~/.dotfiles/config/hypr/colors.lua"
post_hook = "hyprctl reload"

[templates.kitty]
input_path = '~/.dotfiles/config/matugen/templates/kitty.conf'
output_path = '~/.config/kitty/themes/Matugen.conf'
post_hook = "kitty +kitten themes --reload-in=all Matugen"